# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(1, 'MY_BUSINESS')])),
                ('access_token', models.CharField(max_length=171)),
                ('refresh_token', models.CharField(max_length=103)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='googleoauthsession',
            unique_together=set([('user', 'service')]),
        ),
    ]
