# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleoauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleoauthsession',
            name='email',
            field=models.EmailField(default='temporary_email@tmp.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='googleoauthsession',
            unique_together=set([('email', 'service')]),
        ),
    ]
