# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleoauth', '0004_remove_googleoauthsession_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauthsession',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='googleoauthsession',
            name='refresh_token',
            field=models.CharField(max_length=110),
        ),
    ]
