# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposttranslation',
            name='description',
            field=models.TextField(),
        ),
    ]
