# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='language',
            field=models.IntegerField(choices=[(1, 'UK'), (2, 'EN')], default=1),
        ),
    ]
