# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 10:36
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


def set_start_at_field_value(apps, _):
    """
    Migrate the start_at value. Set the default value as December 31 of 2020.
    After setting the default value change the schema and do not allow start_at field
    to be null.
    """

    Announcement = apps.get_model("announcement", "Announcement")
    for announcement in Announcement.objects.all():
        if not announcement.start_at:
            announcement.start_at = datetime.datetime(
                2020, 12, 31, 12, 00, 00, 00, tzinfo=datetime.timezone.utc
            )
            announcement.save()


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_start_at_field_value),
        migrations.AlterField(
            model_name="announcement", name="start_at", field=models.DateTimeField(),
        ),
    ]
