# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('start_at',)},
        ),
    ]
