# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 10:46
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


def set_end_at_field_value(apps, _):
    """
    Set the default value for end_at field.
    Add the 2 hours to the exists start_at field.
    """

    Announcement = apps.get_model("announcement", "Announcement")
    for announcement in Announcement.objects.all():
        announcement.end_at = announcement.start_at + datetime.timedelta(hours=2)
        announcement.end_at.replace(tzinfo=datetime.timezone.utc)
        announcement.save()


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_change_start_at_field_cannot_to_be_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="end_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2020, 12, 31, 13, 00, 00, 00, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_end_at_field_value),
    ]
