# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlemybusiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemybusinessaccount',
            name='email',
            field=models.EmailField(default='temporary_email@tmp.com', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
