# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 12:32
from __future__ import unicode_literals

from django.db import migrations


def set_email_field_value(apps, _):
    """
    Set the default value for email field.
    This email value equals to current user's email value.
    """

    GoogleMyBusinessAccount = apps.get_model("googlemybusiness", "GoogleMyBusinessAccount")
    for account in GoogleMyBusinessAccount.objects.all():
        account.email = account.user.email
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('googlemybusiness', '0002_googlemybusinessaccount_email'),
    ]

    operations = [
        migrations.RunPython(set_email_field_value),
    ]
